export const SET_JANUS = 'SET_JANUS';

export const SET_USERNAME = 'SET_USERNAME';
export const SET_ACTIVE_ROOM = 'SET_ACTIVE_ROOM';
export const SET_REGISTERED_STATUS = 'SET_REGISTERED_STATUS';
export const SET_STREAM = 'SET_STREAM';

export const SET_HANDLE = 'SET_HANDLE';

export const SET_SUBSCRIPTION_HANDLE = 'SET_SUBSCRIPTION_HANDLE';

export const SET_PUBLISHER_LIST = 'SET_PUBLISHER_LIST';
export const DELETE_PUBLISHER = 'DELETE_PUBLISHER';

export const SET_ROOM_LIST_BEGIN = 'SET_ROOM_LIST_BEGIN';
export const SET_ROOM_LIST_SUCCESS = 'SET_ROOM_LIST_SUCCESS';
export const SET_ROOM_LIST_ERROR = 'SET_ROOM_LIST_ERROR';

export const SET_REMOTE_STREAM = 'SET_REMOTE_STREAM';
export const REMOVE_REMOTE_STREAM = 'REMOVE_REMOTE_STREAM';