export const SET_JANUS = 'SET_JANUS';

export const SET_USERNAME = 'SET_USERNAME';
export const SET_ACTIVE_ROOM = 'SET_ACTIVE_ROOM';
export const SET_REGISTERED_STATUS = 'SET_REGISTERED_STATUS';

export const SET_HANDLE = 'SET_HANDLE';

export const SET_PUBLISHER_LIST = 'SET_PUBLISHER_LIST';
export const SET_PUBLISHER = 'SET_PUBLISHER'; 