export const SET_HANDLE = "SET_HANDLE";

export const SET_SUBSCRIPTION = "SET_SUBSCRIPTION";
export const REMOVE_SUBSCRIPTION = "REMOVE_SUBSCRIPTION";
export const SET_SUBSCRIPTION_ICE_STATE = "SET_SUBSCRIPTION_ICE_STATE";
export const SET_SUBSCRIPTION_STREAM = "SET_SUBSCRIPTION_STREAM";

export const SET_ROOM_LIST_BEGIN = "SET_ROOM_LIST_BEGIN";
export const SET_ROOM_LIST_SUCCESS = "SET_ROOM_LIST_SUCCESS";
export const SET_ROOM_LIST_ERROR = "SET_ROOM_LIST_ERROR";
